[package]
name = "kv-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
page_store = { path="../storage_engine/page_store" }
actix-web = "4"