[package]
name = "logchain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
storage = { path = "../storage" }

[dev-dependencies]
tempfile = "3.3.0"