[package]
name = "page_list"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
page_store = { path = "../page_store" }
util = { path = "../../util" }
