name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
  Code coverage:
    - name: Run tests
    - name: rust-grcov
      uses: actions-rs/grcov@v0.1.5
    - run: git config --local user.name "${{ secrets.GITCONFIG_NAME }}"
    - run: git config --local user.email "${{ secrets.GITCONFIG_EMAIL }}"
    - run: git add ./docs/test_coverage/
    - run: git commit -m "update ./docs/test_coverage/" --allow-empty
    - run: git push
